//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteTienda.ServiceGameStore {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGameStore.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GameStoreResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GameStore", ReplyAction="*")]
        ClienteTienda.ServiceGameStore.GameStoreResponse GameStore(ClienteTienda.ServiceGameStore.GameStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GameStore", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteTienda.ServiceGameStore.GameStoreResponse> GameStoreAsync(ClienteTienda.ServiceGameStore.GameStoreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GameStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GameStore", Namespace="http://tempuri.org/", Order=0)]
        public ClienteTienda.ServiceGameStore.GameStoreRequestBody Body;
        
        public GameStoreRequest() {
        }
        
        public GameStoreRequest(ClienteTienda.ServiceGameStore.GameStoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GameStoreRequestBody {
        
        public GameStoreRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GameStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GameStoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteTienda.ServiceGameStore.GameStoreResponseBody Body;
        
        public GameStoreResponse() {
        }
        
        public GameStoreResponse(ClienteTienda.ServiceGameStore.GameStoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GameStoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteTienda.ServiceGameStore.ArrayOfString GameStoreResult;
        
        public GameStoreResponseBody() {
        }
        
        public GameStoreResponseBody(ClienteTienda.ServiceGameStore.ArrayOfString GameStoreResult) {
            this.GameStoreResult = GameStoreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClienteTienda.ServiceGameStore.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClienteTienda.ServiceGameStore.WebService1Soap>, ClienteTienda.ServiceGameStore.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteTienda.ServiceGameStore.GameStoreResponse ClienteTienda.ServiceGameStore.WebService1Soap.GameStore(ClienteTienda.ServiceGameStore.GameStoreRequest request) {
            return base.Channel.GameStore(request);
        }
        
        public ClienteTienda.ServiceGameStore.ArrayOfString GameStore() {
            ClienteTienda.ServiceGameStore.GameStoreRequest inValue = new ClienteTienda.ServiceGameStore.GameStoreRequest();
            inValue.Body = new ClienteTienda.ServiceGameStore.GameStoreRequestBody();
            ClienteTienda.ServiceGameStore.GameStoreResponse retVal = ((ClienteTienda.ServiceGameStore.WebService1Soap)(this)).GameStore(inValue);
            return retVal.Body.GameStoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteTienda.ServiceGameStore.GameStoreResponse> ClienteTienda.ServiceGameStore.WebService1Soap.GameStoreAsync(ClienteTienda.ServiceGameStore.GameStoreRequest request) {
            return base.Channel.GameStoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteTienda.ServiceGameStore.GameStoreResponse> GameStoreAsync() {
            ClienteTienda.ServiceGameStore.GameStoreRequest inValue = new ClienteTienda.ServiceGameStore.GameStoreRequest();
            inValue.Body = new ClienteTienda.ServiceGameStore.GameStoreRequestBody();
            return ((ClienteTienda.ServiceGameStore.WebService1Soap)(this)).GameStoreAsync(inValue);
        }
    }
}
